### ISSUE TITLE
Rhetos doesn't unpack DataMigration folder from package dependencies

### ISSUE THREAD

**Issue by Puzjak** [Rhetos/Rhetos#80] opened 2018-11-15 14:34 UTC
**Describe the bug**
When I add Rhetos.LightDMS, or some other nuget, which has DataMigration folder, in my package dependencies, Rhetos doesn't unpack DataMigration folder, only DslScripts is unpacked (in PackagesCache folder). I also checked Rhetos.DataMigrationScript table and it doesn't contain any of the Rhetos.LightDMS migration scripts.
NuGet Version: 4.6.2.5055

**To Reproduce**
Add new package and in it's .nuspec file add dependency on Rhetos.LightDMS (or some other plugin which has DataMigration folder) and run deploy packages. Data migration scripts from Rhetos.LightDMS won't be executed or unpacked 

**Expected behavior**
DataMigration folder should be unpacked and data migration scripts should be executed.

**Comment by dragofly** [comment] 2018-11-15 14:45
What version of Rhetos and Rhetos.LightDMS are you using?

**Comment by bantolov** [comment] 2018-11-15 15:31
This issue should be further analyzed, but I am guessing that the problem could be caused by the incompatibility of the NuGet version that was used to create the files and the NuGet library version (2.8.3) that Rhetos uses to extract them, considering that this files contains spaces.

**Comment by bantolov** [comment] 2018-11-23 12:33
I have analyzed the issue. The LightDMS v1.5.0 package should be re-packed, either by using NuGet v4.5.1 (or older), or by changing the filenames to remove spaces. The new version should be released as a patch v1.5.1.

It was packed by a newer versions of NuGet, that is not compatible with the older version that is used inside DeployPackages to unpack the files. The breaking change was introduced in NuGet v4.6 and the problem is manifested by skipping the files that contain spaces when extracting the package files.

**Comment by bantolov** [comment] 2019-01-22 13:57
A workaround for the NuGet compatibility issue is implemented in the plugins mentioned above (see [example](https://github.com/Rhetos/AspNetFormsAuth/commit/33640d0dfeadfa4745bd366116c314973d9b8d9a)).
The following **older versions** of the plugins were affected by this issue:
* Rhetos.CommonConcepts: 2.5.0 (fixed in 2.5.1)
* Rhetos.LightDMS: 1.4.0 and 1.5.0 (fixed in 1.5.1)
* Rhetos.AspNetFormsAuth: 2.2.0 (fixed in 2.2.1)
* Rhetos.SimpleSPRTEmail: no versions affected, fixed before the release.

We still need to migrate Rhetos to the a latest version of NuGet client library for a complete solution.

**Comment by bantolov** [comment] 2019-01-22 16:21
I am closing this issue because it was solved by changing the core plugins (see the comment above).
Main cause of these problems is separated to a new issue: #122.

**Closed by bantolov** 2019-01-22 16:21 UTC
Labels: bug
