### ISSUE TITLE
RegExMatch issue

### ISSUE THREAD

**Issue by anchyca** [Rhetos/Rhetos#199] opened 2019-10-03 07:10 UTC
**Describe the bug**
We're having an issue with RegExMatch option - when a regex '\d{1,4}" is used with a message "Code must contain from 1 to 4 digits.", the application shows the message for all code lengths different than 4. So for code of length 1, 2, 3 or 5 or more, the message is shown. Only code length of 4 is accepted as correct.
The only way the RegExMatch is now working is with regex "[0-9][0-9]?[0-9]?[0-9]?".

**To Reproduce**
This is the code which doesn't work:
ShortString Code { Required; Unique; MaxLength 4; DenyUserUpdate; RegExMatch "\d{1,4}" "Code must contain from 1 to 4 digits.."; }

And this one does work:
 ShortString Code { Required; Unique; MaxLength 4; DenyUserUpdate; RegExMatch "[0-9][0-9]?[0-9]?[0-9]?" "Code must contain from 1 to 4 digits."; }

**Error message**
The error message is "Code must contain from 1 to 4 digits." (it shouldn't be shown when it is - described above)

**Expected behavior**
It is expected for RegExMatch to work with "\d{1,4}" and not just with "[0-9][0-9]?[0-9]?[0-9]?"

**Comment by bantolov** [comment] 2019-10-07 10:51
Could you please check the code below, I cannot reproduce the error.

Here is my DSL script:

```c
Module TestRegex
{
    Entity CodeA
    {
        ShortString Code { Unique; MaxLength 4; DenyUserEdit; RegExMatch "\d{1,4}" "Code must contain from 1 to 4 digits.."; }
    }

    Entity CodeB
    {
        ShortString Code { Unique; MaxLength 4; DenyUserEdit; RegExMatch "[0-9][0-9]?[0-9]?[0-9]?" "Code must contain from 1 to 4 digits."; }
    }
}
```

Here is the test C# code (LINQPad):

```cs
void Main()
{
    ConsoleLogger.MinLevel = EventType.Info; // Use "Trace" for more detailed log.
    var rhetosServerPath = Path.GetDirectoryName(Util.CurrentQueryPath);
    Directory.SetCurrentDirectory(rhetosServerPath);
    // Set commitChanges parameter to COMMIT or ROLLBACK the data changes.
    using (var container = new RhetosTestContainer(commitChanges: false))
    {
        var context = container.Resolve<Common.ExecutionContext>();
        var repository = context.Repository;

        var tests = new[]
        {
            "",
            "1",
            "12",
            "123",
            "1234",
            "12345",
            "123456",
        };
        var report = new List<object>();

        foreach (var test in tests)
        {
            try
            {
                repository.TestRegex.CodeA.Insert(new TestRegex.CodeA { Code = test });
                report.Add(new { Option = "CodeA", test, Message = "OK" });
            }
            catch (Exception ex)
            {
                report.Add(new { Option = "CodeA", test, ex.Message });
            }

            try
            {
                repository.TestRegex.CodeB.Insert(new TestRegex.CodeB { Code = test });
                report.Add(new { Option = "CodeB", test, Message = "OK" });
            }
            catch (Exception ex)
            {
                report.Add(new { Option = "CodeB", test, ex.Message });
            }
        }
        
        report.Dump();
    }
}
```

I am getting the same results for both options:

Option | test | Message
-- | -- | --
CodeA |   | It is not allowed to enter {0} because the required property {1} is not set.
CodeB |   | It is not allowed to enter {0} because the required property {1} is not set.
CodeA | 1 | OK
CodeB | 1 | OK
CodeA | 12 | OK
CodeB | 12 | OK
CodeA | 123 | OK
CodeB | 123 | OK
CodeA | 1234 | OK
CodeB | 1234 | OK
CodeA | 12345 | Maximum allowed length of {0} is {1} characters.
CodeB | 12345 | Maximum allowed length of {0} is {1} characters.
CodeA | 123456 | Maximum allowed length of {0} is {1} characters.
CodeB | 123456 | Maximum allowed length of {0} is {1} characters.

**Comment by bantolov** [comment] 2023-12-06 15:27
We can't replicate this issue right now, so we're closing it. If more details come up, we'll check it again.

**Closed by bantolov** 2023-12-06 15:27 UTC
Labels: bug
