### ISSUE TITLE
There are no primary or candidate keys in the referenced table ...

### ISSUE THREAD

**Issue by vinkoSego** [Rhetos/Rhetos#156] opened 2019-05-22 11:10 UTC
**Describe the bug**
Bug is a bit specific, and is not present in other enviroments ( e.g. other developers do not have any problem building rhetos).

**To Reproduce**

```c
    Entity PositionStatus
    {
        AuditAndLoggingAll;

        ShortString Code { Required; }
        ShortString Name { Required; }
        Deactivatable;
    }
    

    Entity PositionStatusService
    {
        AuditAndLoggingAll;
        Reference PositionStatus { Required; }
        Reference Service { Required; }
        
		ItemFilter ServiceLevel1 'x => x.Service.Level.HasValue && x.Service.Level.Value != 1';
		InvalidData ServiceLevel1 'Vrsta usluge mora biti razine 1!';
    }
```

**Error message**
```
[Error] MsSqlExecuter: Unable to execute SQL query:
ALTER TABLE MasterData.PositionStatusService ADD CONSTRAINT FK_PositionStatusService_PositionStatus_PositionStatusID FOREIGN KEY (PositionStatusID) REFERENCES MasterData.PositionStatus (ID) /*ReferencePropertyInfo FK options MasterData.PositionStatusService.PositionStatus*/
[Error] MsSqlExecuter: SqlException has occurred:
Msg 1776, Level 16, State 0, Line 1
There are no primary or candidate keys in the referenced table 'MasterData.PositionStatus' that match the referencing column list in the foreign key 'FK_PositionStatusService_PositionStatus_PositionStatusID'.
Msg 1750, Level 16, State 1, Line 1
Could not create constraint or index. See previous errors.
 System.Data.SqlClient.SqlException (0x80131904): There are no primary or candidate keys in the referenced table 'MasterData.PositionStatus' that match the referencing column list in the foreign key 'FK_PositionStatusService_PositionStatus_PositionStatusID'.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rhetos.Persistence.MsSqlExecuter.<>c__DisplayClass8_0.<ExecuteSql>b__1(DbCommand com) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 95
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 218
ClientConnectionId:bb2d2ad0-f5bd-4cbd-bc62-50d789f83b80
Error Number:1776,State:0,Class:16
[Error] DeployPackages: Rhetos.FrameworkException: SqlException has occurred:
Msg 1776, Level 16, State 0, Line 1
There are no primary or candidate keys in the referenced table 'MasterData.PositionStatus' that match the referencing column list in the foreign key 'FK_PositionStatusService_PositionStatus_PositionStatusID'.
Msg 1750, Level 16, State 1, Line 1
Could not create constraint or index. See previous errors.
 ---> System.Data.SqlClient.SqlException: There are no primary or candidate keys in the referenced table 'MasterData.PositionStatus' that match the referencing column list in the foreign key 'FK_PositionStatusService_PositionStatus_PositionStatusID'.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rhetos.Persistence.MsSqlExecuter.<>c__DisplayClass8_0.<ExecuteSql>b__1(DbCommand com) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 95
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 218
   --- End of inner exception stack trace ---

Server stack trace:
   at Rhetos.Persistence.MsSqlExecuter.SafeExecuteCommand(Action`1 action, Boolean useTransaction) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 229
   at Rhetos.Persistence.MsSqlExecuter.ExecuteSql(IEnumerable`1 commands, Boolean useTransaction, Action`1 beforeExecute, Action`1 afterExecute) in C:\My Projects\Rhetos\Source\Rhetos.Persistence\MsSqlExecuter.cs:line 74
   at Rhetos.Utilities.SqlTransactionBatches.Execute(IEnumerable`1 sqlScripts) in C:\My Projects\Rhetos\Source\Rhetos.Utilities\SqlTransactionBatches.cs:line 120
   at Rhetos.DatabaseGenerator.DatabaseGenerator.ApplyChangesToDatabase(List`1 oldApplications, List`1 newApplications, List`1 toBeRemoved, List`1 toBeInserted) in C:\My Projects\Rhetos\Source\Rhetos.DatabaseGenerator\DatabaseGenerator.cs:line 532
   at Rhetos.DatabaseGenerator.DatabaseGenerator.UpdateDatabaseStructure() in C:\My Projects\Rhetos\Source\Rhetos.DatabaseGenerator\DatabaseGenerator.cs:line 99
   at Rhetos.Deployment.ApplicationGenerator.ExecuteGenerators(Boolean deployDatabaseOnly) in C:\My Projects\Rhetos\Source\Rhetos.Deployment\ApplicationGenerator.cs:line 115

Exception rethrown at [0]:
   at Rhetos.Utilities.ExceptionsUtility.Rethrow(Exception exception) in C:\My Projects\Rhetos\Source\Rhetos.Utilities\ExceptionsUtility.cs:line 58
   at Rhetos.Deployment.ApplicationGenerator.ExecuteGenerators(Boolean deployDatabaseOnly) in C:\My Projects\Rhetos\Source\Rhetos.Deployment\ApplicationGenerator.cs:line 127
   at DeployPackages.Program.GenerateApplication(ILogger logger, DeployArguments arguments) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 184
   at DeployPackages.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 70
Info:

=== ERROR SUMMARY ===
FrameworkException: SqlException has occurred:
Msg 1776, Level 16, State 0, Line 1
There are no primary or candidate keys in the referenced table 'MasterData.PositionStatus' that match the referencing column list in the foreign key 'FK_PositionStatusService_PositionStatus_PositionStatusID'.
Msg 1750, Level 16, State 1, Line 1
Could not create constraint or index. See previous errors.
```

**Expected behavior**
Build should go through and finish succesfully

**Comment by bantolov** [comment] 2019-05-22 13:37
It seems that the table `PositionStatus` is missing primary key, or there is some similar issue.
Please check this table structure and its PK in the database (SQL Server Management Studio => right click on the table => Script table as => Create to).

Did you make any manual modifications of the database structure?

**Comment by bantolov** [comment] 2019-10-18 09:37
I am closing this issue, since it cannot be reproduced.
If you experience the issue again or have any new information on it, please inform us to reopen it.

**Closed by bantolov** 2019-10-18 09:37 UTC
Labels: bug
